### ISSUE TITLE
Link in README is a 404

### ISSUE THREAD

**Issue by spilth** [mikfreedman/notification-muter#1]
https://chrome.google.com/webstore/detail/nadnegkhgmdkedmcmobengbmacbngpma/publish-delayed returns a 404 Page: `The requested URL was not found on this server. That’s all we know.`

**Comment by atishayjain708** [comment]
There is no extra "..../publish-delayed in the link present in the readme. Probably, the author has fixed it already.

**Comment by spilth** [comment]
Fixed by 642ee07112d
